name: docs (build)
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - .pre-commit-config.yaml
      - .github/workflows/docs_build.yml
      - '**.py'
      - '**.ipynb'
      - '**.js'
      - '**.html'
      - uv.lock
      - pyproject.toml
      - '**.rst'
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@f94ec6bedd8674c4426838e6b50417d36b6ab231
        with:
          version: "0.5.21"
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@8039c45ed9a312fba91f3399cd0605ba2ebfe93c
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --dev --group docs

      - name: Build docs
        run: cd docs && rm -rf source/reference/api/_autosummary && uv run make html
